### ISSUE TITLE
您好，数据集链接失效了。请问可以更新一下吗？

### ISSUE THREAD

**Issue by xxzcc** [Anleeno-Xu/Benchmark-For-Underwater-Image-Dataset#1]

**Comment by Anleeno-Xu** [comment]
It's all available, just remove the 'index.html'.

**Comment by xxzcc** [comment]
"该链接已超过访问人数上限，可联系分享者重新分享"， UPRC2020 dataset is not available. 
![image](https://user-images.githubusercontent.com/20204693/149627305-f6f764f3-a079-4afc-81d1-079d25e7eb1f.png)

**Comment by Anleeno-Xu** [comment]
@xxzcc It's updated.
